### ISSUE TITLE
Support for Zabbix 7.2

### ISSUE THREAD

**Issue by QuoxelNet** [TheNetworkGuy/netbox-zabbix-sync#91]
After upgrading Zabbix to 7.2.1, the following message appears in the log:
`Traceback (most recent call last):
  File "/opt/netbox-zabbix-sync/netbox_zabbix_sync.py", line 286, in <module>
    main(args)
  File "/opt/netbox-zabbix-sync/netbox_zabbix_sync.py", line 120, in main
    zabbix = ZabbixAPI(
TypeError: ZabbixAPI.__init__() got an unexpected keyword argument 'ssl_context'`

As far as i know the API has been changed, no login is required anymore. From now on every request requires an API Key.

**Comment by TheNetworkGuy** [comment]
Seems to check out given these release notes: https://github.com/zabbix/python-zabbix-utils/releases/tag/v2.0.2

So its not a Zabbix issue but rather a zabbix_utils library change. A quick fix would be modifying the requirements.txt file and referencing https://github.com/zabbix/python-zabbix-utils/releases/tag/v2.0.1. After that we can update the code and work on documentation.

@q1x Thoughts?

**Comment by q1x** [comment]
Yes, let's update to the newer version of zabbix_utils.

**Comment by TheNetworkGuy** [comment]
Given that this was a quick fix i've pushed it straight to main. I'll work on a seperate branch for the following tasks:

Revert change in requirements.txt, reference to latest version of zabbix_utils
Update documentation to drop support for Zabbix 6.4.
Make code logic that prevents username / password login for Zabbix versions 7.2 and above.
Make some supporting code to log a disaster message when Zabbix 6.4 or lower is detected or non-token login on >=7.2.

**Comment by QuoxelNet** [comment]
Sorry, I'm very busy at the moment...
I started a short test, but got an error:
`Traceback (most recent call last):
  File "/opt/netbox-zabbix-sync/netbox_zabbix_sync.py", line 287, in <module>
    main(args)
  File "/opt/netbox-zabbix-sync/netbox_zabbix_sync.py", line 193, in main
    vm.ConsistencyCheck(zabbix_groups, zabbix_templates,
  File "/opt/netbox-zabbix-sync/modules/device.py", line 585, in ConsistencyCheck
    for group in host["groups"]:
KeyError: 'groups'
`
Unfortunately there was no time until now to debug it...

**Comment by TheNetworkGuy** [comment]
Seems to be the same bug that was mentioned in #93. A fix has already been made, the final step is pushing it to main :) Thanks for your feedback!

**Comment by QuoxelNet** [comment]
Thanks for the fix :) Works like a charm now...
